### ISSUE TITLE
Add a variable system, allowing for layouts to be further customised or even...

### ISSUE THREAD

**Issue by strawmelonjuice** [CynthiaWebsiteEngine/Mini#22]
A variable system should be added using something like this
```toml
[variables]
abc = "yes."
def = { url = "http://definitely" }
ghi = { path = "./undoubtedly.txt" }
```
and the values of this, would be added to the model.others dict on the client.

It would allow layouts to be further customized than they can be right now, and maybe even allows for a 'custom' layout using some template languaging.
